pipeline {
  agent any
  stages {
    stage('Create Artifacts') {
      steps {
        sh 'echo "Create Artifacts"'
      }
    }
    stage('Deploy') {
      parallel {
        stage('Single Setup') {
          steps {
            sh 'echo "Deploy Single"'
          }
        }
        stage('Cluster Setup') {
          steps {
            sh 'echo "Deploy Cluster"'
          }
        }
      }
    }
    stage('Test') {
      parallel {
        stage('BE') {
          steps {
            sh 'echo "BE Tests Run"'
          }
        }
        stage('UI') {
          steps {
            sh 'echo "Run UI Tests"'
          }
        }
      }
    }
    stage('Publish Build') {
      steps {
        sh 'echo "Publish build"'
      }
    }
  }
}
